- name: Update Windows
  hosts: all
  remote_user: sa_ansible

  tasks:

  - name: Install Windows Update
    win_shell: .\multi_machine_win_update.ps1 > C:\Code\install_update\install_update.log
    become: yes
    become_method: runas
    args:
      chdir: C:\Code\install_update

# EOF
